version: '3.7'

services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'peakon/s3-cache']
    volumes:
      - ".:/plugin:ro"
    
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    # volumes:
      # - "./.localstack:/tmp/localstack"
      # - "/var/run/docker.sock:/var/run/docker.sock"
